pipeline {
 agent any

 stages {

  stage('Build & Test') {
   steps {
    dir('DevopsLab/calculator-app') {
     sh 'mvn clean test'
    }
   }
  }

  stage('Package JAR') {
   steps {
    dir('DevopsLab/calculator-app') {
     sh 'mvn package'
    }
   }
  }

 }

 post {
  success {
   archiveArtifacts artifacts: 'DevopsLab/calculator-app/target/*.jar'
  }
 }
}

