pipeline {
 agent any

 stages {

  stage('Build & Test') {
   steps {
    sh 'mvn clean test'
   }
  }

  stage('Package JAR') {
   steps {
    sh 'mvn package'
   }
  }

 }

 post {
  success {
   archiveArtifacts artifacts: 'target/*.jar'
  }
 }
}
